export const trendingHotels = [
    {
        img: 'https://www.travelandleisure.com/thmb/ZLQtQj_t4ZrphuJHNMF6OKT4Seg=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/mahali-mzuri-001-TOPHOTELSWB21-599a7f3e882b4ec9bef98fce099a8483.jpg',
        hotelTitle: '',
        price: '510.00',
        address: 'Masai Mara, Kenya',
        city: 'Sehore',
        District: 'Bhopal',
        State: 'Madhya Pradesh',
        Country: 'India',
        name: 'Mahali Mzuri',
        rating: 5,
        shortDescription: `Part of the Virgin Limited Edition collection, Sir Richard Branson's majestic safari camp in the Masai Mara is "just perfect," according to one voter.`
    },
    {
        img: 'https://www.travelandleisure.com/thmb/o9GfLPGALXXGJaf-FjTbCpI0ofM=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/nayara-tented-camp-002-TOPHOTELSWB21-8b8d953410eb40c492d7011f24bc30e5.jpg',
        hotelTitle: '',
        price: '565.00',
        address: 'Arenal Volcano National Park, Costa Rica',
        city: 'Sehore',
        District: 'Bhopal',
        State: 'Madhya Pradesh',
        Country: 'India',
        name: 'Nayara Tented Camp',
        rating: 4,
        shortDescription: `The most recent entry to the Nayara brand has all the details covered. Cliff-top safari tents have spacious bathrooms with soaking tubs, private decks.`
    },
    {
        img: 'https://www.travelandleisure.com/thmb/kQgSOGe_B6K0k0_fZatkqlK8K5s=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/taj-holiday-village-012-TOPHOTELSWB21-7a3f0490cff54f669ef2e3eea6bfc9ea.jpg',
        hotelTitle: '',
        price: '540.00',
        address: 'Goa, India',
        city: 'Sehore',
        District: 'Bhopal',
        State: 'Madhya Pradesh',
        Country: 'India',
        name: 'Taj Holiday Village Resort & Spa',
        rating: 3,
        shortDescription: `At this 28-acre resort, charming, well-equipped beachfront cottages with terra-cotta roofs overlook the Arabian Sea.`
    },
    {
        img: 'https://www.travelandleisure.com/thmb/zC_z-UrTT78BpN0tkntgXnjTtqs=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/capella-bangkok-004-TOPHOTELSWB21-fc4a3afc3272422799a46f5d08c0be4e.jpg',
        hotelTitle: '',
        price: '510.00',
        address: 'Bangkok',
        city: 'Sehore',
        District: 'Bhopal',
        State: 'Madhya Pradesh',
        Country: 'India',
        name: 'Capella Bangkok',
        rating: 5,
        shortDescription: `Situated on the east bank of the Chao Phraya River, this new urban retreat offers impressive views of the lively Thai capital.`
    },
    {
        img: 'https://www.travelandleisure.com/thmb/ZfP9ubuxQT55cXqVLcZTxmi9N-k=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/temple-house-009-TOPHOTELSWB21-68c30af647e644a2bd9385484028aa87.jpg',
        hotelTitle: '',
        price: '515.00',
        address: 'Chengdu, China',
        city: 'Sehore',
        District: 'Bhopal',
        State: 'Madhya Pradesh',
        Country: 'India',
        name: 'The Temple House',
        rating: 5,
        shortDescription: `Part of the Virgin Limited Edition collection, Sir Richard Branson's majestic safari camp in the Masai Mara is "just perfect," according to one voter.`
    },
    {
        img: 'https://www.travelandleisure.com/thmb/jbBurXpA1aEfGnVrH7TgDP0a4IM=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/hotel-paracas-011-TOPHOTELSWB21-a7556a093cae4e7ca56ae34fa63aab21.jpg',
        hotelTitle: '',
        price: '549.00',
        address: 'Paracas, Peru',
        city: 'Sehore',
        District: 'Bhopal',
        State: 'Madhya Pradesh',
        Country: 'India',
        name: 'Hotel Paracas, a Luxury Collection Resort',
        rating: 4,
        shortDescription: `Part of the Virgin Limited Edition collection, Sir Richard Branson's majestic safari camp in the Masai Mara is "just perfect," according to one voter.`
    },
    {
        img: 'https://www.travelandleisure.com/thmb/zK-h-UVbPhVACO_NywnqlEZLhVM=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/kamalame-cay-007-TOPHOTELSWB21-c617cd9161814797a9f6d7f501040613.jpg',
        hotelTitle: '',
        price: '510.00',
        address: 'Bali, Indonesia',
        city: 'Sehore',
        District: 'Bhopal',
        State: 'Madhya Pradesh',
        Country: 'India',
        name: 'Capella Ubud',
        rating: 4,
        shortDescription: `Last year's Top 100 Hotels winner, this glamorous, Bill Bensley–designed resort features a dramatic suspension bridge leading to 22 tented`
    },
    {
        img: 'https://www.travelandleisure.com/thmb/rJBe8h1cWILuvOhuc2_sa_WGwKg=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/oberoi-udaivilas-008-TOPHOTELSWB21-a0bb1fe5da4a4aebab5c76bd0e672860.jpg',
        hotelTitle: '',
        price: '525.00',
        address: 'Auberge Resorts Collection, Santorini, Greece',
        city: 'Sehore',
        District: 'Bhopal',
        State: 'Madhya Pradesh',
        Country: 'India',
        name: 'Grace Hotel',
        rating: 4,
        shortDescription: `This whitewashed resort, tucked away on the quieter side of Santorini, has unobstructed views of the sparkling Aegean, minus the crowds found elsewhere.`
    }
]

// Tours Data
export const trendingTours = [
    {
        img: '',
        title : 'Adventour',
        price: '510.00',
        city: 'Neemuch',
        district: 'Neemuch',
        state: 'Madhya Pradesh',
        name: 'StoneCastle, Window Castle and Bath of Neemuch',
        rating: '5',
    },
    {
        img: '',
        title : 'Destination Vacation',
        price: '510.00',
        city: 'Neemuch',
        district: 'Neemuch',
        state: 'Madhya Pradesh',
        name: 'StoneCastle, Window Castle and Bath of Neemuch',
        rating: '5',
    },
    {
        img: '',
        title : 'Hop-on, Hop-off',
        price: '510.00',
        city: 'Neemuch',
        district: 'Neemuch',
        state: 'Madhya Pradesh',
        name: 'StoneCastle, Window Castle and Bath of Neemuch',
        rating: '5',
    },
    {
        img: '',
        title : 'Mind the Gap',
        price: '510.00',
        city: 'Neemuch',
        district: 'Neemuch',
        state: 'Madhya Pradesh',
        name: 'StoneCastle, Window Castle and Bath of Neemuch',
        rating: '5',
    },
    {
        img: '',
        title : 'Green Escapes',
        price: '510.00',
        city: 'Neemuch',
        district: 'Neemuch',
        state: 'Madhya Pradesh',
        name: 'StoneCastle, Window Castle and Bath of Neemuch',
        rating: '5',
    },
    {
        img: '',
        title : 'City Sightseeing',
        price: '510.00',
        city: 'Neemuch',
        district: 'Neemuch',
        state: 'Madhya Pradesh',
        name: 'StoneCastle, Window Castle and Bath of Neemuch',
        rating: '5',
    },
    {
        img: '',
        title : 'The Landmark Tour',
        price: '510.00',
        city: 'Neemuch',
        district: 'Neemuch',
        state: 'Madhya Pradesh',
        name: 'StoneCastle, Window Castle and Bath of Neemuch',
        rating: '5',
    },
    {
        img: '',
        title : 'Keep Calm and Travel On',
        price: '510.00',
        city: 'Neemuch',
        district: 'Neemuch',
        state: 'Madhya Pradesh',
        name: 'StoneCastle, Window Castle and Bath of Neemuch',
        rating: '5',
    },
]
